# Generated by Django 5.1.3 on 2025-01-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('company_name', models.CharField(max_length=255)),
                ('students_placed', models.IntegerField()),
                ('average_package', models.FloatField()),
                ('highest_package', models.FloatField()),
                ('role_offered', models.CharField(max_length=255)),
                ('recruitment_type', models.CharField(choices=[('On-campus', 'On-campus'), ('Off-campus', 'Off-campus')], max_length=50)),
            ],
        ),
    ]
