# Generated by Django 5.1.5 on 2025-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100, verbose_name='Name')),
                ('ubatch', models.CharField(max_length=20, verbose_name='Batch')),
                ('uroll_no', models.CharField(max_length=50, unique=True, verbose_name='Roll Number')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='Smart Card ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('upass', models.CharField(max_length=128, verbose_name='Password')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
