# Generated by Django 5.1.5 on 2025-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ubatch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='upass',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='uroll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
