# Generated by Django 5.1.4 on 2025-01-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidyapath_project', '0004_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='batch',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
